let teamMembers = [
  {
    name: "Marcos",
    surname: "Lambir Torres",
    age: 30,
    city: "Franchuski",
    hobby: "Rascarme",
    favoriteFood: "Pasta",
    favoriteVideoGame: "Lol",
    favoriteFilm: "Titanic",
    favoriteBook: "Memorias del Agua",
    petName: "Turi",
  },
  {
    name: "Esteve",
    surname: "Mogas Silva",
    age: 28,
    city: "Granollers",
    hobby: "Escalar",
    favoriteFood: "Croquetas",
    favoriteVideoGame: "Lol",
    favoriteFilm: "Origen",
    favoriteBook: "",
    petName: "",
  },
  {
    name: "Manuel",
    surname: "Benitez",
    age: 29,
    city: "Palma",
    hobby: "Ski",
    favoriteFood: "Empanadas",
    favoriteVideoGame: "Catan",
    favoriteFilm: "",
    favoriteBook: "Shantaram",
    petName: "Shaka, Shiva, Mechi",
  },
  {
    name: "Marta",
    surname: "Miras Méndez",
    age: 21,
    city: "Madrid",
    hobby: "Papiroflexia",
    favoriteFood: "Sushi",
    favoriteVideoGame: "PUBG",
    favoriteFilm: "Avatar",
    favoriteBook: "Loco por ella",
    petName: "Mochi",
  },
];
